name: deploy en Vps

on:
    push:
        branches:
           - master


jobs:
    deploy:
        runs-on: ubuntu-latest

        #Define entorno y clona el repo en el VPS volatil
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
          # instalamos sshpass
            - name: Install sshpass
              run: sudo apt-get install sshpass -y

            - name: Create .ssh directory
              run: mkdir -p ~/.ssh

            - name: Add remote host to known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          


