name: deploy en Vps

on:
    push:
        branches:
           - master


jobs:
    deploy:
        runs-on: ubuntu-latest

        #Define entorno y clona el repo en el VPS volatil
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
          # instalamos sshpass
            - name: Install sshpass
              run: sudo apt-get install sshpass -y
            # creamos la carpeta ssh
            - name: Create .ssh directory
              run: mkdir -p ~/.ssh
            # añadimos el known_host
            - name: Add remote host to known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            - name: execute command on vps
              env:
                SSHPASS: ${{ secrets.SSH_PASSWORD }}
              run: sshpass -e ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 stop camawey && cd basic-deploy && git pull && npm i && pm2 start camawey &"
          
        

